-- 코드를 작성해주세요

SELECT E.ID, E.GENOTYPE, P.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS E INNER JOIN (SELECT ID, GENOTYPE FROM ECOLI_DATA) AS P
ON E.PARENT_ID = P.ID
WHERE E.GENOTYPE & P.GENOTYPE = P.GENOTYPE
ORDER BY E.ID