-- 코드를 작성해주세요

SELECT B.Y AS YEAR,
B.M - SIZE_OF_COLONY AS YEAR_DEV,
A.ID AS ID

FROM ECOLI_DATA AS A, (SELECT MAX(SIZE_OF_COLONY) AS M, YEAR(DIFFERENTIATION_DATE) AS Y FROM ECOLI_DATA GROUP BY Y) AS B

WHERE B.Y = YEAR(A.DIFFERENTIATION_DATE)

ORDER BY B.Y ASC, YEAR_DEV ASC